swiftlint_version: 0.24.2

opt_in_rules:
- array_init
- attributes
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- colon
- comma
- compiler_protocol_init
- contains_over_first_not_nil
- control_statement
- cyclomatic_complexity
- discarded_notification_center_observer
- discouraged_direct_init
- dynamic_inline
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- explicit_type_interface
- extension_access_modifier
- fatal_error_message
- file_length
- first_where
- for_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_parameter_count
- generic_type_name
- identifier_name
- implicit_getter
- implicit_return
- implicitly_unwrapped_optional
- is_disjoint
- joined_default_parameter
- large_tuple
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- let_var_whitespace
- line_length
- literal_expression_end_indentation
- mark
- multiline_arguments
- multiline_parameters
- multiple_closures_with_trailing_closure
- nesting
- nimble_operator
- no_grouping_extension
- notification_center_detachment
- object_literal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_super_call
- protocol_property_accessors_order
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_void_return
- redundant_string_enum_value
- required_enum_case
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- sorted_imports
- statement_position
- strict_fileprivate
- syntactic_sugar
- todo
- trailing_closure
- trailing_comma
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- type_name
- unused_closure_parameter
- unused_enumerated
- unneeded_parentheses_in_closure_argument
- unused_optional_binding
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- void_return
- weak_delegate
- xctfail_message
- yoda_condition

disabled_rules:
- custom_rules
- conditional_returns_on_newline
- discouraged_object_literal
- explicit_acl
- explicit_enum_raw_value
- explicit_top_level_acl
- file_header
- no_extension_access_modifier
- number_separator
- prefixed_toplevel_constant
- switch_case_on_newline

included:
- Sources
- Tests

private_outlet:
  allow_private_set: true

identifier_name:
  excluded:
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
